version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OLLAMA_API_URL=http://ollama:8080
      - PORT=${PORT}  # Render asigna dinámicamente el puerto
    env_file:
      - .env  # Asegúrate de que este archivo exista
    volumes:
      - .:/app
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:3.1
    ports:
      - "8080:8080"  # Mapea el puerto para el entorno local
    restart: always
    volumes:
      - ./ollama_data:/data  # Asegúrate de que la ruta exista
